apiVersion: v1
kind: Service
metadata:
  name: <%= name %>
  labels:
    name: <%= name %>
spec:
  type: LoadBalancer # this assumes you're exposing this service to the outside world
  ports:
    - name: <%= name %>
      port: 80 # this assumes you're exposing this service to the outside world
      targetPort: <%= port %>
      protocol: TCP
  selector:
    role: backend
    app: <%= name %>
