apiVersion: v1
kind: ReplicationController
metadata:
  name: <%= name %>
spec:
  replicas: 1
  selector:
    role: backend
    app: <%= name %>
    version: 0.0.1
  template:
    metadata:
      labels:
        role: backend
        app: <%= name %>
        version: 0.0.1
    spec:
      containers:
        - name: <%= name %>
          image: <%= dockerHandle %>/<%= name %>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: <%= port %>
